### ISSUE TITLE
add ability to harvest citations from https://arcticdata.io/publications/ 

### ISSUE THREAD

**Issue by jeanetteclark** [DataONEorg/scythe#1]
We need to grab citations from this list periodically and add them to the metrics service

**Comment by mbjones** [comment]
I think it would be better if we converted all of these to citations in the metrics DB, and then replace the page with one that shows all Arctic Data Center citations from Rushi's tool. The citation list on https://arcticdata.io/catalog/profile should show every citation we know about.  Then, as long as new citations are added via the UI to the metrics database, they will automatically show up on the citation page.

**Comment by jeanetteclark** [comment]
ah yeah that makes sense. The package could have a generic function where you pass it a list of DOI pairs and it spits out the JSON blob needed for the metrics DB. Then we would just need to grab the content from the page and pass it to that function

**Comment by jeanetteclark** [comment]
closing this since:

1. there aren't many citations on this list
2. this issue is more appropriate for an Arctic Data Center specific repo
